CRITICAL - 2022-04-14 00:52:21 --> file_get_contents(): php_network_getaddresses: getaddrinfo failed: No such host is known. 
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 593)
#1 C:\xampp\htdocs\FAH\app\Controllers\UserHome.php(593): file_get_contents('https://fahback...')
#2 C:\xampp\htdocs\FAH\system\CodeIgniter.php(824): App\Controllers\UserHome->vendor_home()
#3 C:\xampp\htdocs\FAH\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserHome))
#4 C:\xampp\htdocs\FAH\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\FAH\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
